all: model 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015

model:
	python model.py

clean:
	rm nar.db

2004:
	python fetch.py http://nar.oxfordjournals.org/content/32/suppl_1.toc

2005:
	python fetch.py http://nar.oxfordjournals.org/content/vol33/suppl_1/index.dtl

2006:
	python fetch.py http://nar.oxfordjournals.org/content/vol34/suppl_1/index.dtl

2007:
	python fetch.py http://nar.oxfordjournals.org/content/vol35/suppl_1/index.dtl

2008:
	python fetch.py http://nar.oxfordjournals.org/content/vol36/suppl_1/index.dtl

2009:
	python fetch.py http://nar.oxfordjournals.org/content/vol37/suppl_1/index.dtl

2010:
	python fetch.py http://nar.oxfordjournals.org/content/vol38/suppl_1/index.dtl

2011:
	python fetch.py http://nar.oxfordjournals.org/content/vol39/suppl_1/index.dtl

2012:
	python fetch.py http://nar.oxfordjournals.org/content/vol40/issueD1/index.dtl

2013:
	python fetch.py http://nar.oxfordjournals.org/content/vol41/issueD1/index.dtl

2014:
	python fetch.py http://nar.oxfordjournals.org/content/vol42/issueD1/index.dtl

2015:
	python fetch.py http://nar.oxfordjournals.org/content/vol43/issueD1/index.dtl

